"""Criado banco de dados

Revision ID: 653ec87494b2
Revises: 
Create Date: 2025-09-14 10:48:58.177093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653ec87494b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compromisso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('horario', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data', 'horario', name='uq_agendamento_data_horario')
    )
    with op.batch_alter_table('compromisso', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_compromisso_data'), ['data'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compromisso', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_compromisso_data'))

    op.drop_table('compromisso')
    # ### end Alembic commands ###
